### ISSUE TITLE
Some circuits that include extcalls behave unexpectedly when simulated through Verilator

### ISSUE THREAD

**Issue by mbty** [mit-plv/koika#2]
The underlying problem seems to be that `cuttlec` treats extcalls like normal Kôika code when targetting Verilator, ignoring side effects.

For instance, unconditional calls to external modules with side effects are optimized away when the result of the extcall is left unused. For a minimal example of this behavior, see [this commit](https://github.com/mbty/koika/tree/f7f18831cc2b0853ecb5577371e291160143f99a) on my fork. I modified the RISC-V example, adding an external module printing a value to terminal for both Cuttlesim and Verilator and calling it from the `tick` function in `RVCore.v`. `make cuttlesim-tests` quickly fills the output with messages, while the output of the tests ran by `make verilator-tests` is left unchanged. The commit 9638936 stores the result to a debug register, and in this case the behavior of Cuttlesim and Verilator are equivalent.

Another instance of this problem can be seen by nesting an extcall inside an if block, in which case the call is triggered without regard to the condition in some situations. See commit 9f1853a for a minimal example of this behavior (once again, the core of the example is in the `tick` function). Commit 65621bd is a slightly more complex example showing that the effects of calls to `write<n>` present in the same blocks as the triggered extcalls are ignored. Commit 0e34888 shows that binding the result of the extcall to another debug register somehow fixes that behavior. Maybe in that case the optimizer manages to remove the whole block? Commit 65621bd is quite similar to 0e34888, but in this case the condition starts as true and the write inside the if block makes it wrong for future calls. Although the value of the extcall is still stored in a register unrelated to the condition, this time the situation seems to be too complex for the optimizer and Verilator ends up printing a message on each tick. It looks like whenever the extcall can't be entirely removed through optimization, it is just triggered. Is this why `Maybe`s are used as arguments to extcalls, with some repetition between the `valid` field and the conditions already checked in the context of the calls? Couldn't values be passed directly to extcalls and `Maybe`s be generated automatically for Verilator at compile time based on the context of the call? I guess this is a feature that was never fully integrated and that functions well enough for its current purpose but I am interested in getting it to work in what I feel would be a cleaner way and would happily contribute to that end.

**Comment by cpitclaudel** [comment]
Hi @mbty! Your analysis is quite right: in Kôika's current model, extcalls are assumed to be pure (the Sigma in the semantics gives a pure model of each extcall, though see [1] below).  The idea is that your Kôika circuit is really a combinatorial net between register inputs and register outputs.

There are currently three ways to get side effects from inside a Kôika circuits: plug the inputs and outputs of the net into something else than registers; this is complicated to do and it requires quite a bit of code surgery; use an "external rule" by tagging one of the rules as external in the introp package; this will expose all the wires coming into the rule and going out of it as external wires on the generated module, and it's quite unpleasant to work with because it's a lot of wires (all the read/write wires in addition to data0 and data1), and it throws the optimizer off.  The last option is what we do now in the RISCV core, as you saw — namely, we use external functions.

The problem with extcalls, as you saw, is that they are not assumed to be stateful, so if they can be proved to have no observable effects inside Kôika, they are eliminated [2]; and additionally, no care is taken to prevent them from running when they are under conditionals.

The current way the memory bus is written in the RISCV core is a good summary of what the "best practice" is wrt using extcalls.  In particular, you need manually lift the guards (the conditions that might cause the enclosing rule to fail) for each extcall, passing them in as a function call argument.

[1] There's a cute trick that gives a semantic justification to this, btw: since the formal semantics are single-cycle, you can actually change the concrete Sigma between consecutive cycles, which allows you to model extfuns changing external state.  I think @stellamplau experimented with that briefly in the past.

[2] Although I purposefully made the optimizer not be too smart in this case, so as long as the result is a bit_t of size > 0 and eventually stored in some register, the call should survive.

> Is this why Maybes are used as arguments to extcalls, with some repetition between the valid field and the conditions already checked in the context of the calls?

That's exactly right.  

> Couldn't values be passed directly to extcalls and Maybes be generated automatically for Verilator at compile time based on the context of the call?

It's actually a very tricky (but very interesting) problem, which @threonorm is working on right now.  The problem is to avoid creating combinational cycles.  Take this example:

```coq
if some_extfun(x) then fail
else pass
```

We'd like to compute a boolean condition that tells `some_extfun` whether the rule has failed, so that it knows whether it should perform its stateful actions.  But here, "whether the rule fails" depends on the value *returned* by `some_extfun`…

There are all sorts of issues like this, and coming up with a general theory to rule them out isn't trivial.  Maybe @threonorm can provide more details on his current efforts building a proper module system, and I'm sure he'd be happy to see whether his design can accommodate the use cases you have in mind.

In the meantime, my recommendation would be to have a separate rule implementing interaction with the outside world; make sure that this rule never fails, and that it passes extfuns appropriate flags to indicate whether their arguments are ready.  It's painful, but if you isolate things neatly it's quite manageable.

(For simulation you can cheat, btw: the optimizer there marks functions as impure, so it always calls them, and it handles conditionals etc. "properly", in the sense that it doesn't call a function if it's under a condition that evaluates to false).

**Comment by mbty** [comment]
Hi @cpitclaudel and thanks a lot for the explanation.

> ```coq
> if some_extfun(x) then fail
> else pass
> ```
> We'd like to compute a boolean condition that tells some_extfun whether the rule has failed, so that it knows whether it should perform its stateful actions. But here, "whether the rule fails" depends on the value returned by some_extfun…

That explains a lot, `fail` changes everything. Does this problem only arise in rules where at least one the guards of a `fail` is impure on at least one path of execution or are there other such situations?

Maybe it would make sense to restrict the allowed definitions according to an easy to grasp and cheap to check heuristic, like something along the lines of "no fail should be conditioned on something impure", where the following items could be tagged as impure:
- extcalls;
- variables with (a value last set to something impure or last set in an impure context) on at least one path;
- expressions where at least one of the operands is impure;
- `if-then-else` or `match` where the value returned by at least one branch is impure;
- `read1(x)` following a `write0(x, y)`, where `y` is impure, on at least one path;
- functions/module methods returning impure values on at least one path;
- `get`/`getbits(struct, f)` following a `subst`/`substbits(struct, f', i)`, where `i` is impure, on at least one path (`f` and `f'` distinct on purpose, for homogeneity of treatment with structs returned from functions/module methods calls);
- something similar for `pack`/`unpack`;
- whatever else I forgot.

Sure, setting the nth bit (and the nth bit only) of a register to something impure means that it should still be possible to condition a `fail` on any other bit of that register without contradiction. Similarly, assuming a register `r : bits_t 8` and a rule that fails whenever `read1(r)` has exactly four bits set to one, running `write0(r, !read0(r))` in it or not depending on the result of some extcall does not have an impact on the failure of the rule (as `has_four_true_bits(r)` => `has_four_true_bits(~r)`). Both of these situations wouldn't be allowed following the heuristic described above. The general rule is that the failure of a rule should not depend on something impure. However, save for requesting for each rule a proof of the fact that its failure or success is not impacted by the impure elements it contains, which would likely be cumbersome in practice, I don't see how to allow the construction of all the rules where the purity requirement is respected and of these rules only. Losing some nuance for convenience of development and use seems like an acceptable trade-off to me, and the workarounds currently available would still be there for the situations where no other choice remain.

All in all, this indeed is a tricky problem and even that kind of heuristic seems to require a fair amount of work to set up compared to what I first believed possible. I'm curious to see how this will end up being managed in the module system you mentioned.

> In the meantime, my recommendation would be to have a separate rule implementing interaction with the outside world; make sure that this rule never fails, and that it passes extfuns appropriate flags to indicate whether their arguments are ready. It's painful, but if you isolate things neatly it's quite manageable.

Thank you, this helped me solve my issue easily.

**Comment by cpitclaudel** [comment]
> Does this problem only arise in rules where at least one the guards of a fail is impure on at least one path of execution or are there other such situations?

I think so — of o fail or of a read or write that may fail.

> "no fail should be conditioned on something impure"

At the very least it could be a nice static check to have, and I think it wouldn't be super hard.  I also *think* the current uses of impure extfuns would pass that check, since they are at the very end of the rules, which is good evidence in favor of it.

> where the following items could be tagged as impure:

Interestingly, the simulator already has do do such an analysis, because it converts non-shortcircuiting calculations into short-circuiting ones (in Kôika boolean ands are not short-circuiting, but for readability we still want to translate them to C++ &&, which does short-circuit, so impurities have to be lifted out).

> Sure, setting the nth bit (and the nth bit only) of a register to something impure means that it should still be possible to condition a fail on any other bit of that register without contradiction. 

That gets pretty hard pretty quick, in the presence of data-dependent reads/writes.  Bluespec (unlike Kôika) uses fancy analyses of this kind to compute a conflict matrix and rule out conflicts statically, whereas Kôika does it dynamically, and we've found the dynamic approach much nicer in terms of proofs and reasoning (the heuristics of Bluespec are essentially part of the semantics, since you need to understand them to know what will happen in each execution cycle).  So, I'm a bit wary of adding fancy heuristics.

On the other hand, one nice thing about being a DSL inside of Coq is that we should be able to allow users to prove that a given pattern is safe if a heuristic doesn't realize it.

> Thank you, this helped me solve my issue easily.

Good to hear.  Do let us know if you make something public, we'll be excited to link to it!  And if you run into issues or have more questions, please do feel free to ask :)
